리그레션~분류까지 KNN,DT,앙상블등 각각에 대해 실습을 다시 복습합니다.

# 환경설정 및 파일 불러오기

In [1]:
# 라이브러리 호출
import numpy as np
import pandas as pd

In [2]:
# 데이터 불러오기
cars = pd.read_csv("5.cars.csv")
cars.head()

speed  battery
0      4        2
1      4       10
2      7        4
3      7       22
4      8       16

In [3]:
shop = pd.read_csv("5.Shop_rental.csv")
shop.head()

dist  office  home  station    co2   room   age     pop  road  mange  \
0  0.00632    18.0  2.31        0  0.538  6.575  65.2  4.0900     1    296   
1  0.02731     0.0  7.07        0  0.469  6.421  78.9  4.9671     2    242   
2  0.02729     0.0  7.07        0  0.469  7.185  61.1  4.9671     2    242   
3  0.03237     0.0  2.18        0  0.458  6.998  45.8  6.0622     3    222   
4  0.06905     0.0  2.18        0  0.458  7.147  54.2  6.0622     3    222   

    kid  rental  
0  4.98    24.0  
1  9.14    21.6  
2  4.03    34.7  
3  2.94    33.4  
4  5.33    36.2

In [4]:
internet = pd.read_csv("6.internet.csv")
internet.head()

customer  fail  subcompany  gender   age  op_time area
0         1     0           3    male  22.0   7.2500    S
1         2     1           1  female  38.0  71.2833    C
2         3     1           3  female  26.0   7.9250    S
3         4     1           1  female  35.0  53.1000    S
4         5     0           3    male  35.0   8.0500    S

# 1. Regression

## 1-1. 단순회귀분석

In [5]:
from sklearn.model_selection import train_test_split ## 훈련테스트셋 나누기
from sklearn.linear_model import LinearRegression    ## 다중회귀분석
from sklearn.metrics import mean_squared_error       ## 평가지표

In [6]:
X = cars.drop(columns = ["battery"], axis = 1)
y = cars["battery"]

print("y형태:", y.shape)
print("X형태:", X.shape)

print("y타입:", type(y))
print("X타입:", type(X))

y형태: (50,)
X형태: (50, 1)
y타입: <class 'pandas.core.series.Series'>
X타입: <class 'pandas.core.frame.DataFrame'>


In [7]:
# 전체에서 train : test = 8 : 2 로 데이터셋을 분류
train_x  ,test_x  ,train_y  ,test_y   =  train_test_split(X, y, test_size = 0.2   )
print(train_x.shape)
print(test_x.shape)

(40, 1)
(10, 1)


In [8]:
# 선형회귀분석 모델 선언
model = LinearRegression()

# 생성된 모델로 학습
model.fit(train_x,train_y)

# 학습한 모델로 테스트셋의 데이터를 예측
test_pred = model.predict(test_x)
test_pred

array([47.65630567, 47.65630567, 51.28693593, 73.07071744, 33.13378466,
       40.39504517, 33.13378466, 58.54819643, 22.2418939 , 22.2418939 ])

In [9]:
test_y

29     40
28     32
34     84
48    120
15     26
24     26
16     34
42     64
7      26
8      34
Name: battery, dtype: int64

In [10]:
# 테스트셋으로 예측한 Y값과 실제 값을 비교하여 오차 확인하기(평가지표: RMSE)
mean_squared_error(test_y, test_pred, squared = False)

20.042949300703555

In [11]:
from sklearn.metrics import r2_score
print(r2_score(test_y, test_pred)) ## 평가지표를 R2로 했을 때

0.5484467687260319


In [12]:
test_x

speed
29     17
28     17
34     18
48     24
15     13
24     15
16     13
42     20
7      10
8      10

## 1-2. 다중회귀분석

In [13]:
# station 데이터 더미변수화
dummy_var = ['station']

for dum in dummy_var:
  dummies = pd.get_dummies(shop[dum], prefix=dum, drop_first=False)
  new_data = pd.concat([shop, dummies], axis=1)
new_data.head()

dist  office  home  station    co2   room   age     pop  road  mange  \
0  0.00632    18.0  2.31        0  0.538  6.575  65.2  4.0900     1    296   
1  0.02731     0.0  7.07        0  0.469  6.421  78.9  4.9671     2    242   
2  0.02729     0.0  7.07        0  0.469  7.185  61.1  4.9671     2    242   
3  0.03237     0.0  2.18        0  0.458  6.998  45.8  6.0622     3    222   
4  0.06905     0.0  2.18        0  0.458  7.147  54.2  6.0622     3    222   

    kid  rental  station_0  station_1  
0  4.98    24.0          1          0  
1  9.14    21.6          1          0  
2  4.03    34.7          1          0  
3  2.94    33.4          1          0  
4  5.33    36.2          1          0

In [14]:
# 더미변수 station은 drop하고 station_0과 station_1만 남기기
new_data = new_data.drop(columns = ["station"])
new_data.head()

dist  office  home    co2   room   age     pop  road  mange   kid  \
0  0.00632    18.0  2.31  0.538  6.575  65.2  4.0900     1    296  4.98   
1  0.02731     0.0  7.07  0.469  6.421  78.9  4.9671     2    242  9.14   
2  0.02729     0.0  7.07  0.469  7.185  61.1  4.9671     2    242  4.03   
3  0.03237     0.0  2.18  0.458  6.998  45.8  6.0622     3    222  2.94   
4  0.06905     0.0  2.18  0.458  7.147  54.2  6.0622     3    222  5.33   

   rental  station_0  station_1  
0    24.0          1          0  
1    21.6          1          0  
2    34.7          1          0  
3    33.4          1          0  
4    36.2          1          0

In [15]:
# features와 target을 X,y로 분리: rental값을 예측하기 위해 X값에서는 drop, y값에 넣어줌

X = new_data.drop('rental', axis=1)
y = new_data['rental']

# 전체에서 train : test = 7 : 3 으로 나눕니다.
train_x, test_x, train_y, test_y = train_test_split(X, y, test_size=0.3, random_state=1)

In [16]:
# 모델 준비 및 학습
model = LinearRegression()
model.fit(train_x, train_y)

LinearRegression()

In [17]:
new_data

dist  office   home    co2   room   age     pop  road  mange   kid  \
0    0.00632    18.0   2.31  0.538  6.575  65.2  4.0900     1    296  4.98   
1    0.02731     0.0   7.07  0.469  6.421  78.9  4.9671     2    242  9.14   
2    0.02729     0.0   7.07  0.469  7.185  61.1  4.9671     2    242  4.03   
3    0.03237     0.0   2.18  0.458  6.998  45.8  6.0622     3    222  2.94   
4    0.06905     0.0   2.18  0.458  7.147  54.2  6.0622     3    222  5.33   
..       ...     ...    ...    ...    ...   ...     ...   ...    ...   ...   
501  0.06263     0.0  11.93  0.573  6.593  69.1  2.4786     1    273  9.67   
502  0.04527     0.0  11.93  0.573  6.120  76.7  2.2875     1    273  9.08   
503  0.06076     0.0  11.93  0.573  6.976  91.0  2.1675     1    273  5.64   
504  0.10959     0.0  11.93  0.573  6.794  89.3  2.3889     1    273  6.48   
505  0.04741     0.0  11.93  0.573  6.030  80.8  2.5050     1    273  7.88   

     rental  station_0  station_1  
0      24.0          1          0  
1      21.6          1          0  
2      34.7          1          0  
3      33.4          1          0  
4      36.2          1          0  
..      ...        ...        ...  
501    22.4          1          0  
502    20.6          1          0  
503    23.9          1          0  
504    22.0          1          0  
505    11.9          1          0  

[506 rows x 13 columns]

In [18]:
# 예측값을 뽑자. 예측. 모델.predict.. test_x만으로 예측함
test_pred = model.predict(test_x)

In [19]:
print("RMSE:", mean_squared_error(test_y, test_pred, squared=False))
print("R2:", r2_score(test_y, test_pred))

RMSE: 4.818544653343475
R2: 0.7466750040237926


## 1-3. MinMax 정규화 후 LR

In [20]:
# MinMax 정규화
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(train_x) # fit( )을 수행하면 min과 max의 범위를 정하게 됩니다. 
X_train_transformed = scaler.transform(train_x)

In [21]:
# LR로 training
model.fit(X_train_transformed, train_y)

LinearRegression()

In [22]:
# 예측값 확인
X_test_transformed = scaler.transform(test_x)
test_pred = model.predict(X_test_transformed)

In [23]:
# 평가하기
print("RMSE:",mean_squared_error(test_y, test_pred, squared=False))
print("R2:", r2_score(test_y, test_pred))

RMSE: 4.818544653343443
R2: 0.7466750040237959


## 1-4. KNN

In [24]:
# KNN 모델 선언
from sklearn.neighbors import KNeighborsRegressor
model_knn = KNeighborsRegressor(n_neighbors = 3)

In [25]:
model_knn = KNeighborsRegressor(n_neighbors = 3)

In [26]:
#학습
model_knn.fit(X_train_transformed, train_y)

#테스트
test_pred_knn = model_knn.predict(X_test_transformed)

In [27]:
# 평가하기
print("RMSE:",mean_squared_error(test_y, test_pred_knn, squared=False))
print("R2:", r2_score(test_y, test_pred_knn))

RMSE: 4.392004131646242
R2: 0.7895389423654446


## 1-5. XG Boost

In [28]:
!pip install XGboost

In [29]:
# XGB 모델선언
from xgboost import XGBRegressor
model_xg = XGBRegressor()

In [30]:
# XGB train
model_xg.fit(X_train_transformed, train_y)

# 테스트
test_pred_xg = model_xg.predict(X_test_transformed)

[06:01:50] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


In [31]:
# 평가하기
print("RMSE:",mean_squared_error(test_y, test_pred_xg, squared=False))
print("R2:", r2_score(test_y, test_pred_xg))

RMSE: 2.7667126413806926
R2: 0.9164830977508645


## 1-6. Decision Tree

In [32]:
#DT모델선언
from sklearn.tree import DecisionTreeRegressor
model_DT = DecisionTreeRegressor()

In [33]:
#학습
model_DT.fit(X_train_transformed, train_y)

#테스트
test_pred_DT = model_DT.predict(X_test_transformed)

In [34]:
# 평가하기
print("RMSE:",mean_squared_error(test_y, test_pred_DT, squared=False))
print("R2:", r2_score(test_y, test_pred_DT))

RMSE: 4.145455660307917
R2: 0.8125045136907285


# 2. Classification

In [35]:
# "internet" 데이터 전처리

drop_vars = ['customer']
df = internet.drop(drop_vars, axis=1)
df.head()

df.loc[df.area.isnull(), 'area'] = 'S'
df['age'].value_counts(dropna=False)
df = df.dropna(subset=['age'], inplace=False)

## 더미변수화
dummy_var = ['subcompany', 'gender','area']
df_dummy = df.copy()
for dum in dummy_var:
    dummies = pd.get_dummies(df[dum], prefix=dum, drop_first=False)
    df_dummy = pd.concat([df_dummy, dummies], axis=1)

df_dummy = df_dummy.drop(['subcompany', 'gender','area'], axis=1)

In [36]:
# 데이터 나누기
y = df_dummy["fail"]
x = df_dummy.drop('fail', axis=1)

train_x, val_x, train_y, val_y = train_test_split(x, y, test_size=0.2, random_state=1)

In [37]:
# 스케일링
scaler = MinMaxScaler()

scaler.fit(train_x)

train_x = scaler.transform(train_x)
val_x = scaler.transform(val_x)

## 2-1. KNN Classification

In [38]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

#모델링
model_knn = KNeighborsClassifier(n_neighbors = 4)
model_knn.fit(train_x, train_y)

KNeighborsClassifier(n_neighbors=4)

In [39]:
val_pred = model_knn.predict(val_x)

print(confusion_matrix(val_y, val_pred))
print(classification_report(val_y, val_pred))

accuracy_knn = accuracy_score(val_y, val_pred)

print(accuracy_knn)

[[81  5]
 [21 36]]
              precision    recall  f1-score   support

           0       0.79      0.94      0.86        86
           1       0.88      0.63      0.73        57

    accuracy                           0.82       143
   macro avg       0.84      0.79      0.80       143
weighted avg       0.83      0.82      0.81       143

0.8181818181818182


## 2-2. Decision Tree

In [40]:
from sklearn.tree import DecisionTreeClassifier

model_dt = DecisionTreeClassifier()
model_dt.fit(train_x, train_y)

DecisionTreeClassifier()

In [41]:
val_pred = model_dt.predict(val_x)

print(confusion_matrix(val_y, val_pred))
print(classification_report(val_y, val_pred))
accuracy_dt = accuracy_score(val_y, val_pred)
print(accuracy_dt)

[[74 12]
 [11 46]]
              precision    recall  f1-score   support

           0       0.87      0.86      0.87        86
           1       0.79      0.81      0.80        57

    accuracy                           0.84       143
   macro avg       0.83      0.83      0.83       143
weighted avg       0.84      0.84      0.84       143

0.8391608391608392


## 2-3. Random Forest

In [42]:
from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier(n_estimators = 15)
model_rf.fit(train_x, train_y)

RandomForestClassifier(n_estimators=15)

In [43]:
val_pred = model_rf.predict(val_x)

print(confusion_matrix(val_y, val_pred))
print(classification_report(val_y, val_pred))

accuracy_rf = accuracy_score(val_y, val_pred)

print(accuracy_rf)

[[76 10]
 [14 43]]
              precision    recall  f1-score   support

           0       0.84      0.88      0.86        86
           1       0.81      0.75      0.78        57

    accuracy                           0.83       143
   macro avg       0.83      0.82      0.82       143
weighted avg       0.83      0.83      0.83       143

0.8321678321678322


## 2-4. Ensemble(Xgboost)

In [44]:
from xgboost import XGBClassifier

model_xgb = XGBClassifier(n_estimators = 20, learning_rate=0.01)
model_xgb.fit(train_x, train_y)

XGBClassifier(learning_rate=0.01, n_estimators=20)

In [45]:
val_pred = model_xgb.predict(val_x)

print(confusion_matrix(val_y, val_pred))
print(classification_report(val_y, val_pred))

accuracy_xgb = accuracy_score(val_y, val_pred)

print(accuracy_xgb)

[[76 10]
 [17 40]]
              precision    recall  f1-score   support

           0       0.82      0.88      0.85        86
           1       0.80      0.70      0.75        57

    accuracy                           0.81       143
   macro avg       0.81      0.79      0.80       143
weighted avg       0.81      0.81      0.81       143

0.8111888111888111


In [46]:
print("-------------------------------------------")
# print(" 1) 로지스틱 Regression: ",accuracy_logistic_regresssion )
print(" 2) KNN: ",accuracy_knn )
print(" 3) Decision Tree: ",accuracy_dt )
print(" 4) 앙상블_랜덤포레스트: ",accuracy_rf )
print(" 5) 앙상블_XG부스트: ",accuracy_xgb )
print("-------------------------------------------")

-------------------------------------------
 2) KNN:  0.8181818181818182
 3) Decision Tree:  0.8391608391608392
 4) 앙상블_랜덤포레스트:  0.8321678321678322
 5) 앙상블_XG부스트:  0.8111888111888111
-------------------------------------------


# 모델 저장하는 코드

In [47]:
import joblib   
joblib.dump(model, './regression_model.pkl')   ## model = LinearRegression() --> model 저장

['./regression_model.pkl']