<a href="https://colab.research.google.com/github/xoyeon/SMWU_Big-Data-Analysis/blob/main/%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C%EC%9A%B0_%EA%B8%B0%EC%B4%88%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
# 실수 변수형 텐서
s = tf.Variable(1.0)

# 벡터 변수형 텐서
v = tf.Variable(tf.ones((2,)))

# 행렬 변수형 텐서
x = tf.Variable(tf.ones((2,1)))

In [3]:
# 변수 선언
W = tf.Variable(tf.ones(shape=(2,2)), name="W")
b = tf.Variable(tf.zeros(shape=(2)), name="b")

In [4]:
# 수식 정의
@tf.function
def forward(x):
  return W*x+b

In [5]:
out_a = forward([1,0])

print(out_a)           # 텐서 그대로 출력하기
print(out_a.numpy())   # 값만 출력하기

tf.Tensor(
[[1. 0.]
 [1. 0.]], shape=(2, 2), dtype=float32)
[[1. 0.]
 [1. 0.]]


# 1차원 배열 및 텐서를 선언해보자

In [6]:
# 배열을 생성하기 위해 numpy 사용
import numpy as np

In [7]:
# 1차원 배열 생성
array_1d = np.array([1.3, 1, 4.0, 23.99])
print(array_1d)

[ 1.3   1.    4.   23.99]


In [8]:
# 배열 각 요소에 접근하기
print(array_1d[0])

1.3


In [9]:
# 배열을 텐서로 변환하기
tf_1d = tf.convert_to_tensor(array_1d, dtype = tf.float64)
print(tf_1d)

tf.Tensor([ 1.3   1.    4.   23.99], shape=(4,), dtype=float64)


In [10]:
# 텐서의 기본 속성인 rank는 다음과 같이 조회할 수 있다.
print(tf_1d.ndim)

1


In [11]:
# 텐서의 차원은 다음과 같이 튜플 형식으로 조회된다.
print(tf_1d.shape[0])

4


In [12]:
# 텐서의 형상은 하나의 행에 네 개의 열이 있다는 의미다.
# 텐서의 자료 구조는 다음과 같이 조회할 수 있다.
print(tf_1d.dtype)

<dtype: 'float64'>


In [13]:
# 일차원 수열 텐서를 만들 때는 range 또는 linspace 등의 메서드 사용
ex_tf = tf.range(5)
print(ex_tf)
print(ex_tf[0])
print(ex_tf[1])
print(ex_tf[2])
print(ex_tf[3])

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [14]:
# 0 또는 1로 구성 된 텐서
ones = tf.zeros((2,3))
print(ones)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


# 2차원 텐서를 선언해보자

In [15]:
# 2차원 배열 및 텐서 만들기
array_2d = np.array([(1,2,3,4),
                     (4,5,6,7),
                     (8,9,10,11),
                     (12,13,14,15)])
print(array_2d)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [16]:
# constant 상수로 바꿔줌
tensor_2d = tf.constant(array_2d)
print(tensor_2d)

tf.Tensor(
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]], shape=(4, 4), dtype=int64)


In [17]:
tf_3d = np.array([[[1,2], [3,4], [5,6], [7,8]]])
print(tf_3d)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [18]:
print(tf_3d[0,3,1])

8
